imagenet_templates = [
    "a bad photo of a {}.",
    "a photo of many {}.",
    "a sculpture of a {}.",
    "a photo of the hard to see {}.",
    "a low resolution photo of the {}.",
    "a rendering of a {}.",
    "graffiti of a {}.",
    "a bad photo of the {}.",
    "a cropped photo of the {}.",
    "a tattoo of a {}.",
    "the embroidered {}.",
    "a photo of a hard to see {}.",
    "a bright photo of a {}.",
    "a photo of a clean {}.",
    "a photo of a dirty {}.",
    "a dark photo of the {}.",
    "a drawing of a {}.",
    "a photo of my {}.",
    "the plastic {}.",
    "a photo of the cool {}.",
    "a close-up photo of a {}.",
    "a black and white photo of the {}.",
    "a painting of the {}.",
    "a painting of a {}.",
    "a pixelated photo of the {}.",
    "a sculpture of the {}.",
    "a bright photo of the {}.",
    "a cropped photo of a {}.",
    "a plastic {}.",
    "a photo of the dirty {}.",
    "a jpeg corrupted photo of a {}.",
    "a blurry photo of the {}.",
    "a photo of the {}.",
    "a good photo of the {}.",
    "a rendering of the {}.",
    "a {} in a video game.",
    "a photo of one {}.",
    "a doodle of a {}.",
    "a close-up photo of the {}.",
    "a photo of a {}.",
    "the origami {}.",
    "the {} in a video game.",
    "a sketch of a {}.",
    "a doodle of the {}.",
    "a origami {}.",
    "a low resolution photo of a {}.",
    "the toy {}.",
    "a rendition of the {}.",
    "a photo of the clean {}.",
    "a photo of a large {}.",
    "a rendition of a {}.",
    "a photo of a nice {}.",
    "a photo of a weird {}.",
    "a blurry photo of a {}.",
    "a cartoon {}.",
    "art of a {}.",
    "a sketch of the {}.",
    "a embroidered {}.",
    "a pixelated photo of a {}.",
    "itap of the {}.",
    "a jpeg corrupted photo of the {}.",
    "a good photo of a {}.",
    "a plushie {}.",
    "a photo of the nice {}.",
    "a photo of the small {}.",
    "a photo of the weird {}.",
    "the cartoon {}.",
    "art of the {}.",
    "a drawing of the {}.",
    "a photo of the large {}.",
    "a black and white photo of a {}.",
    "the plushie {}.",
    "a dark photo of a {}.",
    "itap of a {}.",
    "graffiti of the {}.",
    "a toy {}.",
    "itap of my {}.",
    "a photo of a cool {}.",
    "a photo of a small {}.",
    "a tattoo of the {}.",
]

painting_templates = [
    "{} style oil painting with rough brush strokes and thick impasto texture.",
    "A painting by {}, featuring bold strokes, heavy paint texture, and expressive brushwork.",
    "{} style painting with visible brush marks, layered paint, and a traditional canvas texture.",
    "An oil painting in the style of {}, with thick paint, rough strokes, and vibrant colors.",
    "{} style artwork with expressive brushwork, impasto technique, and rich color variations.",
    "A landscape painting by {}, featuring dynamic brush strokes, textured surfaces, and painterly details.",
    "{} style masterpiece with coarse brushwork, thick layers of paint, and strong color contrasts.",
    "A canvas painting in the style of {}, using rough strokes, visible paint texture, and impressionist techniques.",
    "{} style oil painting characterized by impasto, heavy brush marks, and expressive colors.",
    "A scenic painting by {}, with textured brushwork, thick paint layers, and a handmade canvas appearance.",
    "{} style painting with loose brush strokes, layered pigments, and dramatic painterly texture.",
    "An expressive oil painting created in the style of {}, featuring rough textures and bold color application.",
    "{} style artwork with impressionistic brushwork, thick oil paint, and visible canvas texture.",
    "A traditional oil painting by {}, showing distinctive brush strokes, textured paint, and artistic composition.",
    "{} style painting featuring energetic brushwork, impasto texture, and strong visual movement.",
    "A portrait painting in the style of {}, with rough brush strokes, thick paint, and expressive textures.",
    "{} style landscape painting with swirling brushwork, layered colors, and rich oil paint texture.",
    "An impressionist painting by {}, featuring loose strokes, vibrant pigments, and thick textured paint.",
    "{} style painting with painterly details, uneven brush marks, and three-dimensional paint texture.",
    "{} style painting of the night sky with bold strokes.",
    "{} style landscape of rolling hills with dramatic brushwork.",
    "{} style rural scene with dynamic movement and intensity.",
    "Wheat field under a swirling sky in the style of {}.",
    "{} style transformation of simple cottages into profound scenes.",
    "City painting in {} style.",
    "A museum-quality oil painting in the style of {}, with expressive strokes, impasto layers, and unique color palette."
]

celebrity_templates = [
    "A portrait of {}.",
    "An image capturing {} at a public event.",
    "An oil painting of {}.",
    "A sketch of {}.",
    "{} in an official photo.",
    "{} smiling at the camera during a red carpet event.",
    "{} walking down the street in casual attire.",
    "A close-up of {} on stage during a live performance.",
    "{} posing for the paparazzi in a glamorous outfit.",
    "{} attending a movie premiere in a sleek suit.",
    "Candid shot of {} enjoying a day at the beach.",
    "{} giving an inspiring speech at a charity event.",
    "{} captured laughing during an interview.",
    "{} signing autographs for fans at a public appearance.",
    "A candid moment of {} sipping coffee at a café.",
    "{} performing on stage with a microphone in hand.",
    "A candid shot of {} waving at fans outside a venue.",
    "{} arriving at an award show in a stunning gown.",
    "{} enjoying a quiet moment reading a book.",
    "{} flashing a peace sign while posing for a selfie.",
    "A casual photo of {} walking a dog in the park.",
    "{} sitting in the front row of a fashion show.",
    "A behind-the-scenes shot of {} getting ready for a shoot.",
    "{} walking the runway at a fashion show.",
    "{} dancing on stage at a live concert."
]

template_dict = {
    'instance': imagenet_templates,
    'style': painting_templates,
    'celebrity': celebrity_templates,
}
